#import "ArkDropBridge.h"

// Forward declaration of Swift class - actual implementation linked at runtime
// This allows cinterop to generate bindings without needing the Swift header
@interface ArkDropBridgeSwift : NSObject
+ (void)sendFilesWithRequest:(ArkDropSendFilesRequest *)request
                  completion:(void (^)(id<ArkDropSendFilesBubble> _Nullable, NSError * _Nullable))completion;

+ (void)sendFilesWithRequest:(ArkDropSendFilesRequest *)request
                       bubble:(id<ArkDropSendFilesBubble> _Nullable __autoreleasing * _Nonnull)bubble
                        error:(NSError * _Nullable __autoreleasing * _Nullable)error;

+ (void)receiveFilesWithRequest:(ArkDropReceiveFilesRequest *)request
                          bubble:(id<ArkDropReceiveFilesBubble> _Nullable __autoreleasing * _Nonnull)bubble
                           error:(NSError * _Nullable __autoreleasing * _Nullable)error;
@end

NS_ASSUME_NONNULL_BEGIN

// Request implementations
@implementation ArkDropSenderProfile
- (instancetype)initWithName:(NSString *)name avatarB64:(nullable NSString *)avatarB64 {
    self = [super init];
    if (self) {
        _name = name;
        _avatarB64 = avatarB64;
    }
    return self;
}
@end

@implementation ArkDropSenderFile
- (instancetype)initWithName:(NSString *)name data:(id<ArkDropSenderFileData>)data {
    self = [super init];
    if (self) {
        _name = name;
        _data = data;
    }
    return self;
}
@end

@implementation ArkDropSenderConfig
- (instancetype)initWithChunkSize:(uint64_t)chunkSize parallelStreams:(uint64_t)parallelStreams {
    self = [super init];
    if (self) {
        _chunkSize = chunkSize;
        _parallelStreams = parallelStreams;
    }
    return self;
}
@end

@implementation ArkDropSendFilesRequest
- (instancetype)initWithProfile:(ArkDropSenderProfile *)profile
                          files:(NSArray<ArkDropSenderFile *> *)files
                          config:(nullable ArkDropSenderConfig *)config {
    self = [super init];
    if (self) {
        _profile = profile;
        _files = files;
        _config = config;
    }
    return self;
}
@end

@implementation ArkDropReceiverProfile
- (instancetype)initWithName:(NSString *)name avatarB64:(nullable NSString *)avatarB64 {
    self = [super init];
    if (self) {
        _name = name;
        _avatarB64 = avatarB64;
    }
    return self;
}
@end

@implementation ArkDropReceiverConfig
- (instancetype)initWithChunkSize:(uint64_t)chunkSize parallelStreams:(uint64_t)parallelStreams {
    self = [super init];
    if (self) {
        _chunkSize = chunkSize;
        _parallelStreams = parallelStreams;
    }
    return self;
}
@end

@implementation ArkDropReceiveFilesRequest
- (instancetype)initWithTicket:(NSString *)ticket
                  confirmation:(uint8_t)confirmation
                        profile:(ArkDropReceiverProfile *)profile
                         config:(ArkDropReceiverConfig *)config {
    self = [super init];
    if (self) {
        _ticket = ticket;
        _confirmation = confirmation;
        _profile = profile;
        _config = config;
    }
    return self;
}
@end

// Bridge function implementations will call Swift code
// These are implemented in ArkDropBridge.swift using @objc exports
// The Swift bridging header will be auto-generated by Xcode

@implementation ArkDropBridge

+ (void)sendFilesWithRequest:(ArkDropSendFilesRequest *)request
                  completion:(void (^)(id<ArkDropSendFilesBubble> _Nullable, NSError * _Nullable))completion {
    // Call Swift implementation (non-blocking)
    [ArkDropBridgeSwift sendFilesWithRequest:request completion:completion];
}

+ (void)sendFilesWithRequest:(ArkDropSendFilesRequest *)request
                       bubble:(id<ArkDropSendFilesBubble> _Nullable * _Nonnull)bubble
                        error:(NSError * _Nullable * _Nullable)error {
    // Call Swift implementation
    [ArkDropBridgeSwift sendFilesWithRequest:request bubble:bubble error:error];
}

+ (void)receiveFilesWithRequest:(ArkDropReceiveFilesRequest *)request
                          bubble:(id<ArkDropReceiveFilesBubble> _Nullable * _Nonnull)bubble
                           error:(NSError * _Nullable * _Nullable)error {
    // Call Swift implementation
    [ArkDropBridgeSwift receiveFilesWithRequest:request bubble:bubble error:error];
}

@end

NS_ASSUME_NONNULL_END
